### ISSUE TITLE
[Issue] - total number of entries

### ISSUE THREAD

**Issue by suricloud** [SystemJargon/filters#10]
**Describe the issue**

A clear and concise description of what the issue is as a problem statement.

**Screenshots**

----

**Note**
Hi.

Please also add the total number of entries in your lists.
like this : Number of entries: 178642

* If this is an allowlist-request, there is a seperate issues form for that.
* If this is an issue with AdGuardHome or Pi-Hole, please submit that as an issue on their official repo.

**Comment by SystemJargon** [comment]
Stats are now available [here](https://github.com/SystemJargon/filters/blob/main/stats/list-entries-stats.txt)
