### ISSUE TITLE
[Issue] - Corelist lite

### ISSUE THREAD

**Issue by suricloud** [SystemJargon/filters#12]
**Describe the issue**

Can you generate a Core list list under 300.000 entries

A clear and concise description of what the issue is as a problem statement.

**Screenshots**

----

**Note**

* If this is an allowlist-request, there is a seperate issues form for that.
* If this is an issue with AdGuardHome or Pi-Hole, please submit that as an issue on their official repo.

**Comment by SystemJargon** [comment]
the Core Light list is due to contain less entries on next commit and push (due in < 24 hours).

Any particular reason why you need it to be under 300,000?

**Comment by SystemJargon** [comment]
Core Light: 209873
