### ISSUE TITLE
unblock pbs.twimg.com in core - heavy

### ISSUE THREAD

**Issue by QWIILXEY** [SystemJargon/filters#16]
### Which blocklist are you using from this repo?

Core Heavy

### Specify the domain/s or sub-domain/s to allow

pbs.twimg.com

### Why should the domain/s or sub-domain/s be allowed?

pbs.twimg.com is needed to load media in a twitter post

**Comment by SystemJargon** [comment]
Your allowlist-request for the domain/subdomain has been added to https://raw.githubusercontent.com/SystemJargon/filters/main/allowlist/allowlist-request.txt
