### ISSUE TITLE
unblock apple.com in core heavy

### ISSUE THREAD

**Issue by QWIILXEY** [SystemJargon/filters#18]
### Which blocklist are you using from this repo?

Core Heavy

### Specify the domain/s or sub-domain/s to allow

apple.com

### Why should the domain/s or sub-domain/s be allowed?

false positive

**Comment by SystemJargon** [comment]
My allowlist.txt exclusion should allow apple.com, failing that you would need to add my allowlist which contains the entry you specified.

https://raw.githubusercontent.com/SystemJargon/filters/main/allowlist.txt

or failing that, add custom filtering rules like this to your DNS server or adblock syntax solution,

@@||apple.com^$important

note by using this you're also allowing other subdomains, which could be Advertising, Telemetry or similar. I do not recommend apple.com with an important modifier, rather specify what subdomains.
