### ISSUE TITLE
[Issue] - apple block too agressive in telemetry list

### ISSUE THREAD

**Issue by pallebone** [SystemJargon/filters#4]
**Describe the issue**
telemetry list contains ||apple.com^ which is too aggressive.

**To Reproduce**
||apple.com^ 
blocks entire apple domain without any further inspection or intelligence.

**Expected behavior**
Telemetry list should not block entire domains.

**Additional context**

Is there any consideration that apple domain should be removed from the list? Unsure why the entire domain is considered telemetry.

Kind regards
Pete

**Comment by pallebone** [comment]
No response from list maintainer, closing.

**Comment by SystemJargon** [comment]
Sorry long time no response. I have now removed the line of apple.com via the aggregated source which gets this domain included in the list raised in the issue.
