### ISSUE TITLE
[security list contains domain more suited for porn list:

### ISSUE THREAD

**Issue by pallebone** [SystemJargon/filters#6]
Domain on security list:

||pornhub.com^

should be moved to porn list (possibly others similar)?

kind regards
Pete

**Comment by pallebone** [comment]
No response from list maintainer, closing.

**Comment by SystemJargon** [comment]
Sorry long time no response. I have now added porn.txt as inclusive to act as an allowlist within security.txt (via it's json aggregator). Therefore pornhub.com would not be included in theory. The latest commit after this comment should reflect these changes.
