### ISSUE TITLE
Blocked by CNAME or IP www.logitechg.com -phishing

### ISSUE THREAD

**Issue by Suspectxyzz** [SystemJargon/filters#7]
## Is your feature request related to a problem? Please describe.
Blocked by CNAME or IP `www.logitechg.com` -phishing / `updates.ghub.logitechg.com`
is the program/site from logitec

![image](https://github.com/SystemJargon/filters/assets/45514952/b3fe2015-ced2-4e7e-946e-e1ccd943d4d5)
![image](https://github.com/SystemJargon/filters/assets/45514952/182e29ad-900d-4419-86f4-5de17412a141)

**Comment by SystemJargon** [comment]
Hi,

What list are you using which you have labelled "SystemJargon -phishing"?

If you go into your AdGuardHome instance and browse to "Filters > DNS Blocklists".

**Comment by Suspectxyzz** [comment]
hello, it's quite strange and I looked in the list where it appeared but it was not found(I'm interested, thanks for the support)
`https://raw.githubusercontent.com/SystemJargon/filters/main/phishing.txt`
